name: 'Validate Gradle Wrapper'
on: [push, pull_request]

jobs:
    validation:
        name: 'Validation'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
              with:
                  show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
            - name: Validate checksums
              uses: gradle/actions/wrapper-validation@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0
